export const FETCH_CONTACTS = 'FETCH_CONTACTS';
export const FETCH_SELECTED_CONTACT = 'FETCH_SELECTED_CONTACT';
export const GET_SELECTED_CONTACT = 'GET_SELECTED_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';